### ISSUE TITLE
Fix Chrome Drag n Drop Issue

### ISSUE THREAD

**Issue by ibndias** [zonblade/rich-json-viewer#2]
Drag N Drop issue when using Chrome

Dropbox area flickering on and off.

**Comment by zonblade** [comment]
fixed in latest chrome

**Comment by ibndias** [comment]
Still occurs in latest Chrome and Edge

>Chrome is up to date
Version 140.0.7339.81 (Official Build) (64-bit)

>Microsoft Edge is up to date.
Version 139.0.3405.125 (Official build) (64-bit)
